periodicoOnlineMVC/Controllers/PeriodicoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace periodicoOnlineMVC.Controllers
{
    public class PeriodicoController : Controller
    {
        // GET: Periodico
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ListaNoticia()
        {
            return View();
        }


    }
}

periodicoOnlineMVC/Views/Plantillas/_PlantillaHomeAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@Page.Title</title>
    @RenderSection("head", required: false)
    <!-- Bootstrap Core CSS -->
    <link href="../css/bootstrap.min.css" rel="stylesheet" />

    <!-- MetisMenu CSS -->
    <link href="../css/metisMenu.min.css" rel="stylesheet" />

    <!-- Custom CSS -->
    <link href="../css/sb-admin-2.css" rel="stylesheet" />

    <!-- Custom Fonts -->
    <link href="../css/font-awesome.min.css" rel="stylesheet" type="text/css" />

</head>
<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="../homeAdmin/homeAdmin.aspx">Panel de Administración</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">




                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li>
                            <a href="#"><i class="fa fa-user fa-fw"></i> Perfil de Usuario</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-gear fa-fw"></i> Ajustes</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="../index.aspx"><i class="fa fa-sign-out fa-fw"></i> Cerrar Sesión</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Buscar..." />
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                            <!-- /input-group -->
                        </li>

                        <li>
                            <a href="#"><i class="fa fa-newspaper-o"></i> Noticias<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="../homeAdmin/ingresarNoticia.aspx"><i class="fa fa-plus-circle"></i>  Nueva Noticia</a>
                                </li>
                                <li>
                                    <a href="../homeAdmin/listarNoticias.aspx"><i class="fa fa-list-alt"></i>  Listar Noticias</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>


                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">


                        <h1 class="page-header">
                            @ViewBag.encabezado
                        </h1>



                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <!-- /.row -->

                @if (IsSectionDefined("regionContenido"))
                {
                   @RenderSection("regionContenido")
                }

                

            </div>
            <!-- /.container-fluid -->




        </div>
        <!-- /#page-wrapper -->

    </div>


    @RenderBody()

    <!-- /#wrapper -->
    <!-- jQuery -->
    <script src="../js/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="../js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="../js/metisMenu.min.js"></script>

    <!-- DataTables JavaScript -->
    <script src="../js/jquery.dataTables.min.js"></script>
    <script src="../js/dataTables.bootstrap.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="../js/sb-admin-2.js"></script>


    <script>
        $(document).ready(function () {
            $('#tablaListaNoticias').DataTable({
                responsive: true,
                "columns" : [
                    { "width": "30%" },
                    { "width": "60%" },
                    { "width": "10%" }

                ],
                "language": {
                    "url": "../js/Spanish.json"
                }

            });
        });
    </script>

    @if (IsSectionDefined("regionScript"))
    {
        @RenderSection("regionScript")
    }

</body>
</html>

periodicoOnlineMVC/Views/Plantillas/_PlantillaPeriodico.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@Page.Title</title>
    @RenderSection("head", required: false)
    
    @Styles.Render("~/Content/estiloPeriodico")
 

</head>
<body>

    <div class="wrapper row1">
        <header id="header" class="clear">
            <div id="hgroup">
                <h1><a href="#">Nombre</a></h1>
                <h2>Slogan</h2>
            </div>
            <nav>
                <ul>
                    <li><a href="@Url.Action("Index","Periodico")">Home</a></li>
                    <li><a href="@Url.Action("ListaNoticia","Periodico")">Noticias</a></li>
                    <li><a href="../listaNoticiasMedianas.aspx">Blog</a></li>
                    <li><a href="#">Link 4</a></li>
                    <li class="last"><a href="#">Link 5</a></li>
                </ul>
            </nav>
        </header>
    </div>

    <div class="wrapper row2">
        <div id="container" class="clear">


           @if (IsSectionDefined("regionSlider"))
           {
               @RenderSection("regionSlider")
           }
           else
           {
            <section id="slider"><a href="#"><img src="@Url.Content("~/Content/images/960x360.gif")" alt="" /></a></section>
           }

          


            <div id="homepage">


                @if (IsSectionDefined("regionNoticiasPequenas"))
                {
                    @RenderSection("regionNoticiasPequenas")
                }
                else
                {
                    <section id="services" class="clear">
                        <article class="one_third">
                            <figure>
                                <img src="@Url.Content("~/Content/images/290x180.gif")" width="290" height="180" alt="" />
                                <figcaption>
                                    <h2>Ejemplo de Noticia 1</h2>
                                    <p>&Eacute;ste es el ejemplo de una posible noticia. no es obligaci&oacute;n que sea una noticia real.</p>
                                    <footer class="more"><a href="../noticiaCompleta.aspx">Leer M&aacute;s &raquo;</a></footer>
                                </figcaption>
                            </figure>
                        </article>
                        <article class="one_third">
                            <figure>
                                <img src="@Url.Content("~/Content/images/290x180.gif")" width="290" height="180" alt="" />
                                <figcaption>
                                    <h2>Ejemplo de Noticia 2</h2>
                                    <p>&Eacute;ste&Eacute;ste es el ejemplo de una posible noticia. no es obligaci&oacute;n que sea una noticia real.</p>
                                    <footer class="more"><a href="#">Leer M&aacute;sM&aacute;s &raquo;</a></footer>
                                </figcaption>
                            </figure>
                        </article>
                        <article class="one_third lastbox">
                            <figure>
                                <img src="@Url.Content("~/Content/images/290x180.gif")" width="290" height="180" alt="" />
                                <figcaption>
                                    <h2>Ejemplo de Noticia 3</h2>
                                    <p>&Eacute;ste es el ejemplo de una posible noticia. no es obligaci&oacute;n que sea una noticia real.</p>
                                    <footer class="more"><a href="#">Leer M&aacute;s &raquo;</a></footer>
                                </figcaption>
                            </figure>
                        </article>
                    </section>
                }

             
                @if (IsSectionDefined("regionNoticiaMediana"))
                {
                    @RenderSection("regionNoticiaMediana")
                }
                else
                {
                    <section id="intro" class="last clear">
                        <article>
                            <figure>
                                <img src="@Url.Content("~/Content/images/450x250.gif")" width="450" height="250" alt="" />
                                <figcaption>
                                    <h2>Anticipo de Noticia Importante</h2>
                                    <p>&Eacute;ste es el ejemplo de una posible noticia. no es obligaci&oacuten que sea una noticia real.</p>
                                    <p>Tambi&Eeacute;n puede ser un articulo interesante de lo que quieras contar, ojo, debe tener concordancia con el periodico que vas a crear. tambi&eacute;n puedes hacer referencia a alg&uacute;n <a href="#">Sitio Web</a> o <a href="#">Parte de la misma p&aacute;gina</a>.</p>
                                    <footer class="more"><a href="#">Leer M&aacute;s &raquo;</a></footer>
                                </figcaption>
                            </figure>
                        </article>
                    </section>

                }
            </div>
        </div>
    </div>
    <!-- Footer -->
    <div class="wrapper row3">


        @if (IsSectionDefined("regionGrupodeLink"))
        {
            @RenderSection("regionGrupodeLink")
        }
        else
        {
            <div id="footer" class="clear">
                <!-- Seccion 1 -->
                <section class="one_quarter">
                    <h2 class="title">Link 1</h2>
                    <nav>
                        <ul>
                            <li><a href="#">Ejemplo noticia 1</a></li>
                            <li><a href="#">Ejemplo noticia 2</a></li>
                            <li><a href="#">Ejemplo noticia 3</a></li>
                            <li><a href="#">Ejemplo noticia 4</a></li>
                            <li class="last"><a href="#">Ejemplo noticia 5</a></li>
                        </ul>
                    </nav>
                </section>
                <!-- Seccion 2 -->
                <section class="one_quarter">
                    <h2 class="title">Link 2</h2>
                    <nav>
                        <ul>
                            <li><a href="#">Ejemplo noticia 1</a></li>
                            <li><a href="#">Ejemplo noticia 2</a></li>
                            <li><a href="#">Ejemplo noticia 3</a></li>
                            <li><a href="#">Ejemplo noticia 4</a></li>
                            <li class="last"><a href="#">Ejemplo noticia 5</a></li>
                        </ul>
                    </nav>
                </section>
                <!-- Seccion 3 -->
                <section class="one_quarter">
                    <h2 class="title">Link 3</h2>
                    <nav>
                        <ul>
                            <li><a href="#">Ejemplo noticia 1</a></li>
                            <li><a href="#">Ejemplo noticia 2</a></li>
                            <li><a href="#">Ejemplo noticia 3</a></li>
                            <li><a href="#">Ejemplo noticia 4</a></li>
                            <li class="last"><a href="#">Ejemplo noticia 5</a></li>
                        </ul>
                    </nav>
                </section>
                <!-- Seccion 4 -->
                <section class="one_quarter lastbox">
                    <h2 class="title">Link 4</h2>
                    <nav>
                        <ul>
                            <li><a href="#">Ejemplo noticia 1</a></li>
                            <li><a href="#">Ejemplo noticia 2</a></li>
                            <li><a href="#">Ejemplo noticia 3</a></li>
                            <li><a href="#">Ejemplo noticia 4</a></li>
                            <li class="last"><a href="#">Ejemplo noticia 5</a></li>
                        </ul>
                    </nav>
                </section>
                <!-- / Seccion -->
            </div>
        }
    </div>
    <!-- Copyright -->
    <div class="wrapper row4">
        <footer id="copyright" class="clear">
            <p class="fl_left">Copyright &copy; 2016 - Todos Los Derechos Reservados - <a href="#">Nombre-Apellido</a></p>
            <p class="fl_right"><a href="../homeAdmin/homeAdmin.aspx">Acceso Administrador</a></p>
        </footer>
    </div>

    @RenderBody()

</body>
</html>